#when you want to do the same thing for each target , you dont have to write the same things many time
#just do this

all : f0.o f1.o

f0.o f1.o:
	echo $@
# run the following , you will get what @ means here
