.EXPORT_ALL_VARIABLES:
# this like exports all of vars
# when calling make there are env vars which exists b4 you call make , make creates make vars from all of them

#creating env var :
export env_var_g='saeed'

all:
	echo value of env_var_g as env var = $$env_var_g
	echo value of env_var_g as make var = $(env_var_g)


