# each line starts on new shell 
all:
	@echo first one :
	cd ..
	cat Makefile
	@echo second :
	cd ..;\
	cat Makefile;
	@echo third :
	cd ..; cat Makefile;
	@touch all
# run the app to see the diff of each one

clean:
	rm -f all
