#Add -k when running make to continue running even in the face of errors. Helpful if you want to see all the errors of Make at once.
#Add a - before a command to suppress the error
#<F3>Add -i to make to have this happen for every command.

one:
	# This error will be printed but ignored, and make will continue to run
	-false
	touch one

