#rename the file or dir is possible with this syntax :
# mv {current name of the file} {new name of the file}
# remove :
# rm -f {file name}

a := "something"
b := 'something'
c := something
var_test:
	echo "a is " $(a)
	echo "b is " $(b)
	echo "c is " $(c)
	echo 'b is ' $(b)

# just run make to see what it prints
