#running with commandline arg var
# make var=value
# if you want to change their values you have to use override keyword

override var = test
var0=1

all:
	echo $(var)
	#does not change the command line value
	echo $(var0)

